### ISSUE TITLE
Does not work on Windows

### ISSUE THREAD

**Issue by ghost** [kinkinkijkin/kPMML#18]
```ps
PS C:\Users\naray\GitHub\kPMML\src\kPMML\bin\Release> .\kPMML.exe .\referenceexample3.txt 320
name=laughter
artist=kinkinkijkin
10hz
/env
e1 AHD 50 500 5000
e2 AHD 200 2000 40000
e3 AHD 50 8000 80000
/wav
sin SINE 550 0
/fm
fm1 FM2O e2 1 0 0 0
/mu
gatherer ( FN1 GS1 o+1 CN1 o-1 )8
hunter ( CN1 DS1 FN1 )8
c1 ( sin e1 ( o=3 gatherer hunter )4 )2
c2 ( fm1 e2 ( o=2 gatherer hunter )4 )2
END

Unhandled Exception: System.IO.IOException: The pipe has been ended.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
   at kPMML.kPMML.Main(String[] args) in C:\Users\naray\GitHub\kPMML\src\kPMML\Program.cs:line 351
```
Is it my install of ffmpeg or do I need to change something to make this work?

**Comment by ghost** [comment]
I should note that the release binaries outright didn't work. I had to compile this myself on Windows (which passes without any errors) to get an executable that would tell me the issue.

**Comment by kinkinkijkin** [comment]
ffmpeg has to be in your PATH environment variable.

if it's already in PATH, this is a really confusing issue, as it has worked for others on windows with ffmpeg in PATH.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/7173984/37631687-4b503864-2bc1-11e8-9afe-0c76d993defb.png)
It's not working for me, even in previous binaries. I've added ffmpeg to path and all, but it's still not working for me. I have a feeling it might be my PC anyway and will test this on another PC tomorrow.

**Comment by ghost** [comment]
The only version of kPMML that works on any windows PC for me is the b01 release.

**Comment by kinkinkijkin** [comment]
weird, I don't have a windows dev environment to test and fix this, but this is a high-priority issue in the case that it's not just some freak difference between your system and the expected target system.

Marking
